### ISSUE TITLE
Bugs List

### ISSUE THREAD

**Issue by FastLaneRolePlay** [Manliketjb/qb-documents#1]
I am not sure if any of these have been solved, but I am going to list them incase they haven't for them to further become resolved.

Guards not spawning sometimes which results in Mission not being able to start and or even complete.
Mission just disappearing once you approach the location.
Govern Files not being located where the marker is, which causes the run not to be able to complete.

**Comment by Manliketjb** [comment]
1. guards do spawn all the time, just some of them are located inside stuff around the area (recommend going though the config and playing with some of the settings)
2. the blip disappears but the mission is still going
3. all markers are general locations, not exact locations. because well... GTA 5 waypoints suck

been tested by quite a few people in different servers and works perfect for them. the script itself is really old, this is just the updated, in the future i might revamp/ re do the whole thing.
